-- ===============================================基础视图=================================================
-- 附件查询
CREATE OR REPLACE VIEW ATT_VIEW
AS
SELECT lk.TABLE_NAME, lk.PK_NAME, lk.RECORD_ID, detail.DETAIL_ID AS FJID, detail.ATT_NAME AS FJMC
	, detail.ATT_FORMAT AS FJLX
FROM BSC_ATT_LINK lk
	LEFT JOIN BSC_ATT_DETAIL detail ON lk.DETAIL_ID = detail.DETAIL_ID;

-- 主题最大发布版本号
CREATE OR REPLACE VIEW THEME_MAX_VER
AS
SELECT theme_2.THEME_ID, theme_2.THEME_CODE, GJBZSPLCLX, MAX(VER_NUM) AS VER_NUM
FROM AEA_PAR_THEME_VER aptv_2
	INNER JOIN AEA_PAR_THEME theme_2 ON theme_2.THEME_ID = aptv_2.THEME_ID
WHERE IS_PUBLISH IN ('1', '2', '3')
GROUP BY theme_2.THEME_ID;

-- ===============================================业务视图=================================================
-- --------------------------------------------------------------------------------------------------------
-- 要点说明：
-- 1.辅线下事项作为并行推进事项上传到并行阶段下
-- 2.阶段选择不显示时不上传阶段下事项，阶段作为一个事项上传
-- 3.每个主题都构造一个虚拟的'并行阶段'
-- --------------------------------------------------------------------------------------------------------

-- 3.3.1地方项目审批流程信息表
CREATE OR REPLACE VIEW SPGL_DFXMSPLCXXB_VIEW
AS
SELECT ptv.THEME_VER_ID AS DFSJZJ, '000000' AS XZQHDM, apt.THEME_CODE AS SPLCBM, apt.THEME_NAME AS SPLCMC, ptv.VER_NUM AS SPLCBBH
	, ptv.MODIFY_TIME AS SPLCSXSJ, apt.GJBZSPLCLX AS SPLCLX, ptv.VER_MEMO AS SPLCSM, detail.ATT_NAME AS FJMC, detail.ATT_FORMAT AS FJLX
	, detail.DETAIL_ID AS FJID
	, 1 AS SJYXBS
	, CASE
		WHEN ptv.MODIFY_TIME IS NOT NULL THEN ptv.MODIFY_TIME
		ELSE ptv.CREATE_TIME
	END AS MODIFY_TIME
FROM AEA_PAR_THEME_VER ptv
	INNER JOIN AEA_PAR_THEME apt ON apt.THEME_ID = ptv.THEME_ID
	LEFT JOIN BSC_ATT_LINK lk
	ON lk.RECORD_ID = ptv.THEME_VER_ID
		AND lk.TABLE_NAME = 'AEA_PAR_THEME_VER'
		AND lk.PK_NAME = 'THEME_VER_ID'
	LEFT JOIN BSC_ATT_DETAIL detail ON lk.DETAIL_ID = detail.DETAIL_ID
WHERE ptv.IS_PUBLISH IN (1, 2, 3)
	AND apt.THEME_TYPE IN ('A00001','A00003')
	AND apt.IS_DELETED = '0'
	AND ptv.IS_DELETED = '0';

-- 3.3.2地方项目审批流程阶段信息表
CREATE OR REPLACE VIEW SPGL_DFXMSPLCJDXXB_VIEW
AS
SELECT stage.STAGE_ID AS DFSJZJ, '000000' AS XZQHDM, apt.THEME_CODE AS SPLCBM, ptv.VER_NUM AS SPLCBBH, stage.STAGE_CODE AS SPJDBM
	, stage.STAGE_NAME AS SPJDMC, stage.SORT_NO AS SPJDXH, stage.DYBZSPJDXH AS DYBZSPJDXH, stage.DUE_NUM AS SPJDSX, stage.LCBSXLX AS LCBSXLX
	, 1 AS SJYXBS
	, CASE
		WHEN ptv.MODIFY_TIME IS NOT NULL THEN ptv.MODIFY_TIME
		ELSE ptv.CREATE_TIME
	END AS MODIFY_TIME
FROM AEA_PAR_STAGE stage
	INNER JOIN AEA_PAR_THEME_VER ptv
	ON ptv.THEME_VER_ID = stage.THEME_VER_ID
		AND ptv.IS_PUBLISH IN (1, 2, 3)
		AND ptv.IS_DELETED = '0'
	INNER JOIN AEA_PAR_THEME apt ON apt.THEME_ID = ptv.THEME_ID
		AND apt.THEME_TYPE IN ('A00001','A00003')
		AND apt.IS_DELETED = '0'
WHERE stage.IS_SHOW_ITEM != '0'
	AND stage.IS_NODE = '1'
UNION ALL
SELECT CONCAT(apt.THEME_CODE, '-', ptv.VER_NUM) AS DFSJZJ, '000000' AS XZQHDM
	, apt.THEME_CODE AS SPLCBM, ptv.VER_NUM AS SPLCBBH
	, CONCAT(apt.THEME_CODE, '-', ptv.VER_NUM) AS SPJDBM
	, '并行推进' AS SPJDMC, 5 AS SPJDXH, 5 AS DYBZSPJDXH, 0 AS SPJDSX, 2 AS LCBSXLX
	, 1 AS SJYXBS
	, CASE
		WHEN ptv.MODIFY_TIME IS NOT NULL THEN ptv.MODIFY_TIME
		ELSE ptv.CREATE_TIME
	END AS MODIFY_TIME
FROM AEA_PAR_THEME_VER ptv
	INNER JOIN AEA_PAR_THEME apt ON apt.THEME_ID = ptv.THEME_ID
    AND apt.THEME_TYPE IN ('A00001','A00003')
WHERE ptv.IS_PUBLISH IN (1, 2, 3);

-- 3.3.3地方项目审批流程阶段事项信息表
CREATE OR REPLACE VIEW SPGL_DFXMSPLCJDSXXXB_VIEW
AS
SELECT DFSJZJ, XZQHDM, SPLCBM, SPLCBBH, SPJDXH
	, SPSXBM, SPSXBBH, SPSXMC, DYBZSPSXBM, SFSXGZCNZ
	, BJLX, SQDX, BLJGSDFS, SPSXBLSX, SPBMBM
	, SPBMMC, SFLCBSX, SJYXBS, MODIFY_TIME
FROM (
	SELECT psi.STAGE_ITEM_ID AS DFSJZJ, '000000' AS XZQHDM, apt_123.THEME_CODE AS SPLCBM, aptv_123.VER_NUM AS SPLCBBH
		, CASE
			WHEN psi.IS_OPTION_ITEM = '1' THEN 5
			WHEN stage.IS_NODE IN ('2', '3') THEN 5
			ELSE stage.SORT_NO
		END AS SPJDXH, aib_123.ITEM_CODE AS SPSXBM, aiv_123.VER_NUM AS SPSXBBH, aib_123.ITEM_NAME AS SPSXMC, aib_123.STANDARD_ITEM_CODE AS DYBZSPSXBM
		, aib_123.SFSXGZCNZ AS SFSXGZCNZ
		, CASE aib_123.ITEM_PROPERTY
			WHEN 'LBJ' THEN '3'
			WHEN 'DFJ' THEN '5'
			WHEN 'DBJ' THEN '6'
			WHEN '3' THEN '4'
			ELSE aib_123.ITEM_PROPERTY
		END AS BJLX
		, CASE
			WHEN aib_123.XKDX IS NULL
			OR INSTR(aib_123.XKDX, ',') > 0
			OR length(trim(aib_123.XKDX)) <= 0 THEN '6'
			ELSE aib_123.XKDX
		END AS SQDX
		, CASE
			WHEN length(trim(aib_123.SEND_RESULT_MODE)) > 0 THEN aib_123.SEND_RESULT_MODE
			ELSE '2,3'
		END AS BLJGSDFS, aib_123.DUE_NUM AS SPSXBLSX
		, (
			SELECT ORG_CODE
			FROM OPU_OM_ORG
			WHERE aib_123.ORG_ID = OPU_OM_ORG.ORG_ID
		) AS SPBMBM
		, (
			SELECT ORG_NAME
			FROM OPU_OM_ORG
			WHERE aib_123.ORG_ID = OPU_OM_ORG.ORG_ID
		) AS SPBMMC, aib_123.IS_MILESTONE_ITEM AS SFLCBSX, 1 AS SJYXBS
		, CASE
			WHEN aptv_123.MODIFY_TIME IS NOT NULL THEN aptv_123.MODIFY_TIME
			ELSE aptv_123.CREATE_TIME
		END AS MODIFY_TIME
	FROM aea_par_stage_item psi
		INNER JOIN aea_item_ver ib ON ib.ITEM_VER_ID = psi.ITEM_VER_ID
		INNER JOIN aea_item i ON i.PARENT_ITEM_ID = ib.ITEM_ID
		INNER JOIN aea_item_basic aib_123 ON aib_123.item_id = i.item_id
		INNER JOIN aea_item_ver aiv_123
		ON aiv_123.ITEM_VER_ID = aib_123.ITEM_VER_ID
			AND aiv_123.ITEM_VER_STATUS IN ('1', '2', '3')
			AND aiv_123.IS_DELETED = '0'
		INNER JOIN AEA_PAR_STAGE stage
		ON stage.STAGE_ID = psi.STAGE_ID
			AND stage.IS_DELETED = '0'
		INNER JOIN AEA_PAR_THEME_VER aptv_123
		ON aptv_123.THEME_VER_ID = stage.THEME_VER_ID
			AND aptv_123.IS_PUBLISH IN (1, 2, 3)
			AND aptv_123.IS_DELETED = '0'
		INNER JOIN AEA_PAR_THEME apt_123
		ON apt_123.THEME_ID = aptv_123.THEME_ID
			AND apt_123.THEME_TYPE IN ('A00001', 'A00003')
			AND apt_123.IS_DELETED = '0'
	UNION ALL
	SELECT psi.STAGE_ITEM_ID AS DFSJZJ, '000000' AS XZQHDM, apt_123.THEME_CODE AS SPLCBM, aptv_123.VER_NUM AS SPLCBBH
		, CASE
			WHEN psi.IS_OPTION_ITEM = '1' THEN 5
			WHEN stage.IS_NODE IN ('2', '3') THEN 5
			ELSE stage.SORT_NO
		END AS SPJDXH, aib_123.ITEM_CODE AS SPSXBM, aiv_123.VER_NUM AS SPSXBBH, aib_123.ITEM_NAME AS SPSXMC, aib_123.STANDARD_ITEM_CODE AS DYBZSPSXBM
		, aib_123.SFSXGZCNZ AS SFSXGZCNZ
		, CASE aib_123.ITEM_PROPERTY
			WHEN 'LBJ' THEN '3'
			WHEN 'DFJ' THEN '5'
			WHEN 'DBJ' THEN '6'
			WHEN '3' THEN '4'
			ELSE aib_123.ITEM_PROPERTY
		END AS BJLX
		, CASE
			WHEN aib_123.XKDX IS NULL
			OR INSTR(aib_123.XKDX, ',') > 0
			OR length(trim(aib_123.XKDX)) <= 0 THEN '6'
			ELSE aib_123.XKDX
		END AS SQDX
		, CASE
			WHEN length(trim(aib_123.SEND_RESULT_MODE)) > 0 THEN aib_123.SEND_RESULT_MODE
			ELSE '2,3'
		END AS BLJGSDFS, aib_123.DUE_NUM AS SPSXBLSX
		, (
			SELECT ORG_CODE
			FROM OPU_OM_ORG
			WHERE aib_123.ORG_ID = OPU_OM_ORG.ORG_ID
		) AS SPBMBM
		, (
			SELECT ORG_NAME
			FROM OPU_OM_ORG
			WHERE aib_123.ORG_ID = OPU_OM_ORG.ORG_ID
		) AS SPBMMC, aib_123.IS_MILESTONE_ITEM AS SFLCBSX, 1 AS SJYXBS
		, CASE
			WHEN aptv_123.MODIFY_TIME IS NOT NULL THEN aptv_123.MODIFY_TIME
			ELSE aptv_123.CREATE_TIME
		END AS MODIFY_TIME
	FROM aea_par_stage_item psi
		INNER JOIN aea_item_basic aib_123
		ON psi.ITEM_VER_ID = aib_123.ITEM_VER_ID
			AND aib_123.IS_CATALOG = '0'
		INNER JOIN aea_item_ver aiv_123
		ON aiv_123.ITEM_VER_ID = aib_123.ITEM_VER_ID
			AND aiv_123.ITEM_VER_STATUS IN ('1', '2', '3')
			AND aiv_123.IS_DELETED = '0'
		INNER JOIN AEA_PAR_STAGE stage
		ON stage.STAGE_ID = psi.STAGE_ID
			AND stage.IS_DELETED = '0'
		INNER JOIN AEA_PAR_THEME_VER aptv_123
		ON aptv_123.THEME_VER_ID = stage.THEME_VER_ID
			AND aptv_123.IS_PUBLISH IN (1, 2, 3)
			AND aptv_123.IS_DELETED = '0'
		INNER JOIN AEA_PAR_THEME apt_123
		ON apt_123.THEME_ID = aptv_123.THEME_ID
			AND apt_123.THEME_TYPE IN ('A00001', 'A00003')
			AND apt_123.IS_DELETED = '0'
) a
GROUP BY SPLCBM, SPLCBBH, SPSXBM, SPSXBBH;

-- 3.4.1项目基本信息
CREATE OR REPLACE VIEW SPGL_XMJBXXB_VIEW
AS
SELECT proj.PROJ_INFO_ID AS DFSJZJ, '000000' AS XZQHDM
	, replace(proj.LOCAL_CODE, '#', '-') AS XMDM
	, proj.PROJ_NAME AS XMMC, replace(proj.GCBM, '#', '-') AS GCDM
	, proj.PROJ_NAME AS GCFW
	, (
		SELECT GROUP_CONCAT(p.GCBM)
		FROM AEA_PROJ_INFO p
			INNER JOIN AEA_PARENT_PROJ pp ON pp.PARENT_PROJ_ID = p.PROJ_INFO_ID
		WHERE pp.CHILD_PROJ_ID = proj.PROJ_INFO_ID
	) AS QJDGCDM
	, CASE
		WHEN proj.FINANCIAL_SOURCE = '0' THEN '1'
		WHEN proj.FINANCIAL_SOURCE = '1' THEN '2'
		WHEN proj.FINANCIAL_SOURCE = '2' THEN '3'
		ELSE '3'
	END AS XMTZLY
	, CASE
		WHEN proj.LAND_SOURCE = '0' THEN '1'
		WHEN proj.LAND_SOURCE = '1' THEN '3'
		WHEN proj.LAND_SOURCE = '2' THEN '4'
		WHEN proj.LAND_SOURCE = '3' THEN '2'
		WHEN proj.LAND_SOURCE = '4' THEN '5'
		ELSE '5'
	END AS TDHQFS
	, CASE
		WHEN length(trim(proj.IS_DESIGN_SOLUTION)) > 0 THEN proj.IS_DESIGN_SOLUTION
		ELSE '0'
	END AS TDSFDSJFA
	, CASE
		WHEN length(trim(proj.IS_AREA_ESTIMATE)) > 0 THEN proj.IS_AREA_ESTIMATE
		ELSE '0'
	END AS SFWCQYPG, GJBZSPLCLX AS SPLCLX
	, CASE proj.PROJ_TYPE
		WHEN 'A00001' THEN '1'
		WHEN 'A00002' THEN '2'
		WHEN 'A00003' THEN '3'
		ELSE '1'
	END AS LXLX
	, CASE
		WHEN length(trim(proj.PROJ_CATEGORY)) = 0 THEN NULL
		ELSE proj.PROJ_CATEGORY
	END AS GCFL
	, CASE
		WHEN length(trim(proj.PROJ_NATURE)) > 0 THEN proj.PROJ_NATURE
		ELSE 5
	END AS JSXZ
	, CASE proj.INVEST_TYPE
		WHEN '1' THEN '1'
		WHEN '2' THEN '1'
		WHEN '0' THEN '2'
		ELSE '3'
	END AS XMZJSX
	, CASE
		WHEN length(trim(proj.THE_INDUSTRY)) > 0 THEN proj.THE_INDUSTRY
		ELSE 'A01'
	END AS GBHY
	, CASE
		WHEN length(trim(proj.GB_CODE_YEAR)) > 0 THEN proj.GB_CODE_YEAR
		ELSE '2017'
	END AS GBHYDMFBND
	, CASE
		WHEN length(trim(NSTART_TIME)) > 0 THEN
			CASE
				WHEN length(trim(proj.NSTART_TIME)) = 4 THEN CONCAT(proj.NSTART_TIME, '-01-01')
				WHEN length(trim(proj.NSTART_TIME)) < 9 THEN replace(replace(proj.END_TIME, '月', '-'), '年', '-')
				ELSE replace(replace(proj.NSTART_TIME, '月', '-01'), '年', '-')
			END
		ELSE '1970-01-01'
	END AS NKGSJ
	, CASE
		WHEN length(trim(proj.END_TIME)) > 0 THEN
			CASE
				WHEN length(trim(proj.END_TIME)) = 4 THEN CONCAT(proj.END_TIME, '-12-31')
				WHEN length(trim(proj.END_TIME)) < 9 THEN replace(replace(proj.END_TIME, '月', '-'), '年', '-')
				ELSE replace(replace(proj.END_TIME, '月', '-01'), '年', '-')
			END
		ELSE '1970-12-31'
	END AS NJCSJ, '0' AS XMSFWQBJ, NULL AS XMWQBJSJ
	, CASE
		WHEN length(trim(proj.INVEST_SUM)) > 0 THEN proj.INVEST_SUM
		ELSE 0
	END AS ZTZE
	, CASE
		WHEN length(trim(proj.REGIONALISM)) = 6 THEN proj.REGIONALISM
		WHEN proj.REGIONALISM IS NOT NULL THEN (
			SELECT REGION_NUM
			FROM BSC_DIC_REGION
			WHERE REGION_ID = REGIONALISM
		)
		ELSE '000000'
	END AS JSDDXZQH
	, CASE
		WHEN proj.PROJ_ADDR IS NOT NULL
		AND length(trim(proj.PROJ_ADDR)) > 0 THEN proj.PROJ_ADDR
		ELSE 'xx市'
	END AS JSDD, NULL AS XMJSDDX, NULL AS XMJSDDY
	, CASE
		WHEN length(trim(proj.SCALE_CONTENT)) > 0 THEN proj.SCALE_CONTENT
		ELSE '建设规模：'
	END AS JSGMJNR
	, CASE
		WHEN length(trim(proj.XM_YDMJ)) > 0 THEN proj.XM_YDMJ
		ELSE 0
	END AS YDMJ
	, CASE
		WHEN length(trim(proj.BUILD_AREA_SUM)) > 0 THEN proj.BUILD_AREA_SUM
		ELSE 0
	END AS JZMJ
	, CASE
		WHEN length(trim(proj.PROJECT_CREATE_DATE)) > 0 THEN proj.PROJECT_CREATE_DATE
		ELSE proj.CREATE_TIME
	END AS SBSJ, theme.THEME_CODE AS SPLCBM, theme.VER_NUM AS SPLCBBH, 1 AS SJYXBS
	, CASE
		WHEN proj.MODIFY_TIME IS NULL THEN proj.CREATE_TIME
		ELSE proj.MODIFY_TIME
	END AS MODIFY_TIME
FROM AEA_PROJ_INFO proj
	INNER JOIN THEME_MAX_VER theme ON theme.THEME_ID = proj.THEME_ID
UNION ALL
SELECT ahai123.APPLYINST_PROJ_ID AS DFSJZJ, '000000' AS XZQHDM
	, replace(proj.LOCAL_CODE, '#', '-') AS XMDM
	, proj.PROJ_NAME AS XMMC, replace(proj.GCBM, '#', '-') AS GCDM
	, proj.PROJ_NAME AS GCFW
	, (
		SELECT GROUP_CONCAT(p.GCBM)
		FROM AEA_PROJ_INFO p
			INNER JOIN AEA_PARENT_PROJ pp ON pp.PARENT_PROJ_ID = p.PROJ_INFO_ID
		WHERE pp.CHILD_PROJ_ID = proj.PROJ_INFO_ID
	) AS QJDGCDM
	, CASE
		WHEN proj.FINANCIAL_SOURCE = '0' THEN '1'
		WHEN proj.FINANCIAL_SOURCE = '1' THEN '2'
		WHEN proj.FINANCIAL_SOURCE = '2' THEN '3'
		ELSE '3'
	END AS XMTZLY
	, CASE
		WHEN proj.LAND_SOURCE = '0' THEN '1'
		WHEN proj.LAND_SOURCE = '1' THEN '3'
		WHEN proj.LAND_SOURCE = '2' THEN '4'
		WHEN proj.LAND_SOURCE = '3' THEN '2'
		WHEN proj.LAND_SOURCE = '4' THEN '5'
		ELSE '5'
	END AS TDHQFS
	, CASE
		WHEN length(trim(proj.IS_DESIGN_SOLUTION)) > 0 THEN proj.IS_DESIGN_SOLUTION
		ELSE '0'
	END AS TDSFDSJFA
	, CASE
		WHEN length(trim(proj.IS_AREA_ESTIMATE)) > 0 THEN proj.IS_AREA_ESTIMATE
		ELSE '0'
	END AS SFWCQYPG, theme.GJBZSPLCLX AS SPLCLX
	, CASE proj.PROJ_TYPE
		WHEN 'A00001' THEN '1'
		WHEN 'A00002' THEN '2'
		WHEN 'A00003' THEN '3'
		ELSE '1'
	END AS LXLX
	, CASE
		WHEN length(trim(proj.PROJ_CATEGORY)) = 0 THEN NULL
		ELSE proj.PROJ_CATEGORY
	END AS GCFL
	, CASE
		WHEN length(trim(proj.PROJ_NATURE)) > 0 THEN proj.PROJ_NATURE
		ELSE 5
	END AS JSXZ
	, CASE proj.INVEST_TYPE
		WHEN '1' THEN '1'
		WHEN '2' THEN '1'
		WHEN '0' THEN '2'
		ELSE '3'
	END AS XMZJSX
	, CASE
		WHEN length(trim(proj.THE_INDUSTRY)) > 0 THEN proj.THE_INDUSTRY
		ELSE 'A01'
	END AS GBHY
	, CASE
		WHEN length(trim(proj.GB_CODE_YEAR)) > 0 THEN proj.GB_CODE_YEAR
		ELSE '2017'
	END AS GBHYDMFBND
	, CASE
		WHEN length(trim(NSTART_TIME)) > 0 THEN
			CASE
				WHEN length(trim(proj.NSTART_TIME)) = 4 THEN CONCAT(proj.NSTART_TIME, '-01-01')
				WHEN length(trim(proj.NSTART_TIME)) < 9 THEN replace(replace(proj.END_TIME, '月', '-'), '年', '-')
				ELSE replace(replace(proj.NSTART_TIME, '月', '-01'), '年', '-')
			END
		ELSE '1970-01-01'
	END AS NKGSJ
	, CASE
		WHEN length(trim(proj.END_TIME)) > 0 THEN
			CASE
				WHEN length(trim(proj.END_TIME)) = 4 THEN CONCAT(proj.END_TIME, '-12-31')
				WHEN length(trim(proj.END_TIME)) < 9 THEN replace(replace(proj.END_TIME, '月', '-'), '年', '-')
				ELSE replace(replace(proj.END_TIME, '月', '-01'), '年', '-')
			END
		ELSE '1970-12-31'
	END AS NJCSJ, '0' AS XMSFWQBJ, NULL AS XMWQBJSJ
	, CASE
		WHEN length(trim(proj.INVEST_SUM)) > 0 THEN proj.INVEST_SUM
		ELSE 0
	END AS ZTZE
	, CASE
		WHEN length(trim(proj.REGIONALISM)) = 6 THEN proj.REGIONALISM
		WHEN proj.REGIONALISM IS NOT NULL THEN (
			SELECT REGION_NUM
			FROM BSC_DIC_REGION
			WHERE REGION_ID = REGIONALISM
		)
		ELSE '000000'
	END AS JSDDXZQH
	, CASE
		WHEN proj.PROJ_ADDR IS NOT NULL
		AND length(trim(proj.PROJ_ADDR)) > 0 THEN proj.PROJ_ADDR
		ELSE 'xx市'
	END AS JSDD, NULL AS XMJSDDX, NULL AS XMJSDDY
	, CASE
		WHEN length(trim(proj.SCALE_CONTENT)) > 0 THEN proj.SCALE_CONTENT
		ELSE '建设规模：'
	END AS JSGMJNR
	, CASE
		WHEN length(trim(proj.XM_YDMJ)) > 0 THEN proj.XM_YDMJ
		ELSE 0
	END AS YDMJ
	, CASE
		WHEN length(trim(proj.BUILD_AREA_SUM)) > 0 THEN proj.BUILD_AREA_SUM
		ELSE 0
	END AS JZMJ
	, CASE
		WHEN length(trim(proj.PROJECT_CREATE_DATE)) > 0 THEN proj.PROJECT_CREATE_DATE
		ELSE (
			SELECT CREATE_TIME
			FROM aea_hi_applyinst
			WHERE APPLYINST_ID = ahai123.APPLYINST_ID
		)
	END AS SBSJ, theme.THEME_CODE AS SPLCBM, theme.VER_NUM AS SPLCBBH, 1 AS SJYXBS, ahai123.CREATE_TIME AS MODIFY_TIME
FROM AEA_APPLYINST_PROJ ahai123
	INNER JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = ahai123.PROJ_INFO_ID
	INNER JOIN AEA_HI_PAR_STAGEINST hps ON hps.APPLYINST_ID = ahai123.APPLYINST_ID
	INNER JOIN AEA_PAR_STAGE stage ON stage.STAGE_ID = hps.STAGE_ID
	INNER JOIN AEA_PAR_THEME_VER ptv ON ptv.THEME_VER_ID = hps.THEME_VER_ID
	INNER JOIN AEA_PAR_THEME apt
	ON apt.THEME_ID = ptv.THEME_ID
		AND apt.THEME_TYPE = 'A00002'
	LEFT JOIN THEME_MAX_VER theme ON theme.THEME_ID = proj.THEME_ID;

-- 3.4.2项目单位信息表
CREATE OR REPLACE VIEW SPGL_XMDWXXB_VIEW
AS
SELECT aup.APPLYINST_UNIT_PROJ_ID AS DFSJZJ, '000000' AS XZQHDM
	, replace(proj.LOCAL_CODE, '#', '-') AS XMDM
	, replace(proj.GCBM, '#', '-') AS GCDM
	, unit.UNIFIED_SOCIAL_CREDIT_CODE AS DWTYSHXYDM, unit.APPLICANT AS DWMC
	, CASE
		WHEN up.UNIT_TYPE = '8' THEN '7'
		WHEN length(trim(up.UNIT_TYPE)) > 0 THEN up.UNIT_TYPE
		ELSE '7'
	END AS DWLX
	, CASE up.IS_DELETED
		WHEN '1' THEN '0'
		WHEN '0' THEN '1'
	END AS SJYXBS, aup.CREATE_TIME AS MODIFY_TIME
FROM AEA_APPLYINST_UNIT_PROJ aup
	INNER JOIN AEA_HI_APPLYINST aha ON aha.APPLYINST_ID = aup.APPLYINST_ID
	INNER JOIN AEA_UNIT_PROJ up ON up.UNIT_PROJ_ID = aup.UNIT_PROJ_ID
	INNER JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = up.PROJ_INFO_ID
	INNER JOIN AEA_UNIT_INFO unit ON unit.UNIT_INFO_ID = up.UNIT_INFO_ID;

-- 3.5.1项目审批事项办理信息表
CREATE OR REPLACE VIEW SPGL_XMSPSXBLXXB_VIEW
AS
(SELECT '000000' AS XZQHDM, iteminst.ITEMINST_ID AS DFSJZJ
	, replace(proj.GCBM, '#', '-') AS GCDM
	, aib_123.item_code AS SPSXBM, aiv_123.VER_NUM AS SPSXBBH, apt_123.THEME_CODE AS SPLCBM, aptv_123.VER_NUM AS SPLCBBH, iteminst.ITEMINST_ID AS SPSXSLBM
	, org.ORG_CODE AS SPBMBM, org.ORG_NAME AS SPBMMC
	, CASE aha_123.APPLYINST_SOURCE
		WHEN 'net' THEN 4
		WHEN 'win' THEN 1
	END AS SLFS
	, CASE
		WHEN iteminst.PUBLIC_MODE IS NOT NULL THEN iteminst.PUBLIC_MODE
		ELSE '1'
	END AS GKFS
	, CASE
		WHEN (
			SELECT COUNT(1)
			FROM aea_hi_iteminst
			WHERE STAGEINST_ID = iteminst.STAGEINST_ID
		) > 1 THEN iteminst.STAGEINST_ID
		ELSE NULL
	END AS BLSPSLBM, asti.TIME_LIMIT AS SXBLSX, 1 AS SJYXBS
	, CASE
		WHEN iteminst.CREATE_TIME > asti.CREATE_TIME THEN iteminst.CREATE_TIME
		ELSE asti.CREATE_TIME
	END AS MODIFY_TIME
FROM AEA_HI_ITEMINST iteminst
	INNER JOIN ACT_STO_TIMERULE_INST asti
	ON asti.PROC_INST_ID = iteminst.PROCINST_ID
		AND asti.TIMERULE_INST_TYPE = '1'
	INNER JOIN AEA_HI_PAR_STAGEINST hps ON hps.STAGEINST_ID = iteminst.STAGEINST_ID
	INNER JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = hps.APPLYINST_ID
	INNER JOIN AEA_PAR_STAGE stage
	ON stage.STAGE_ID = hps.STAGE_ID
		AND stage.IS_SHOW_ITEM != '0'
	LEFT JOIN AEA_HI_APPLYINST aha_123 ON aha_123.APPLYINST_ID = hps.APPLYINST_ID
	LEFT JOIN AEA_ITEM_VER aiv_123 ON aiv_123.ITEM_VER_ID = iteminst.ITEM_VER_ID
	LEFT JOIN AEA_ITEM_BASIC aib_123 ON aib_123.ITEM_VER_ID = iteminst.ITEM_VER_ID
	LEFT JOIN AEA_PAR_THEME_VER aptv_123 ON aptv_123.THEME_VER_ID = stage.THEME_VER_ID
	LEFT JOIN AEA_PAR_THEME apt_123 ON apt_123.THEME_ID = aptv_123.THEME_ID
	LEFT JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = aap.PROJ_INFO_ID
	LEFT JOIN OPU_OM_ORG org ON org.ORG_ID = iteminst.APPROVE_ORG_ID)
UNION ALL
(SELECT '000000' AS XZQHDM, iteminst.ITEMINST_ID AS DFSJZJ
	, replace(proj.GCBM, '#', '-') AS GCDM
	, aib_123.item_code AS SPSXBM, aiv_123.VER_NUM AS SPSXBBH, apt_123.THEME_CODE AS SPLCBM, aptv_123.VER_NUM AS SPLCBBH, iteminst.ITEMINST_ID AS SPSXSLBM
	, org.ORG_CODE AS SPBMBM, org.ORG_NAME AS SPBMMC
	, CASE aha_123.APPLYINST_SOURCE
		WHEN 'net' THEN 4
		WHEN 'win' THEN 1
	END AS SLFS
	, CASE
		WHEN iteminst.PUBLIC_MODE IS NOT NULL THEN iteminst.PUBLIC_MODE
		ELSE '1'
	END AS GKFS
	, CASE
		WHEN (
			SELECT COUNT(1)
			FROM aea_hi_iteminst
			WHERE STAGEINST_ID = iteminst.STAGEINST_ID
		) > 1 THEN iteminst.STAGEINST_ID
		ELSE NULL
	END AS BLSPSLBM, asti.TIME_LIMIT AS SXBLSX, 1 AS SJYXBS
	, CASE
		WHEN iteminst.CREATE_TIME > asti.CREATE_TIME THEN iteminst.CREATE_TIME
		ELSE asti.CREATE_TIME
	END AS MODIFY_TIME
FROM AEA_HI_ITEMINST iteminst
	INNER JOIN ACT_STO_TIMERULE_INST asti
	ON asti.PROC_INST_ID = iteminst.PROCINST_ID
		AND asti.TIMERULE_INST_TYPE = '1'
	INNER JOIN AEA_HI_SERIESINST ahs ON ahs.SERIESINST_ID = iteminst.SERIESINST_ID
	INNER JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = ahs.APPLYINST_ID
	LEFT JOIN AEA_PAR_STAGE stage ON stage.STAGE_ID = ahs.STAGE_ID
	LEFT JOIN AEA_HI_APPLYINST aha_123 ON aha_123.APPLYINST_ID = ahs.APPLYINST_ID
	LEFT JOIN AEA_ITEM_VER aiv_123 ON aiv_123.ITEM_VER_ID = iteminst.ITEM_VER_ID
	LEFT JOIN AEA_ITEM_BASIC aib_123 ON aib_123.ITEM_VER_ID = iteminst.ITEM_VER_ID
	LEFT JOIN AEA_PAR_THEME_VER aptv_123 ON aptv_123.THEME_VER_ID = stage.THEME_VER_ID
	LEFT JOIN AEA_PAR_THEME apt_123 ON apt_123.THEME_ID = aptv_123.THEME_ID
	LEFT JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = aap.PROJ_INFO_ID
	LEFT JOIN OPU_OM_ORG org ON org.ORG_ID = iteminst.APPROVE_ORG_ID
WHERE ahs.STAGE_ID IS NOT NULL
	AND NOT EXISTS (
		SELECT 1
		FROM AEA_IM_PROJ_PURCHASE ipp
		WHERE ipp.APPLYINST_ID = ahs.APPLYINST_ID
	))
UNION ALL
(SELECT '000000' AS XZQHDM, iteminst.ITEMINST_ID AS DFSJZJ
	, replace(proj.GCBM, '#', '-') AS GCDM
	, aib_123.item_code AS SPSXBM, aiv_123.VER_NUM AS SPSXBBH, apt_123.THEME_CODE AS SPLCBM, NULL AS SPLCBBH, iteminst.ITEMINST_ID AS SPSXSLBM
	, org.ORG_CODE AS SPBMBM, org.ORG_NAME AS SPBMMC
	, CASE aha_123.APPLYINST_SOURCE
		WHEN 'net' THEN 4
		WHEN 'win' THEN 1
	END AS SLFS
	, CASE
		WHEN iteminst.PUBLIC_MODE IS NOT NULL THEN iteminst.PUBLIC_MODE
		ELSE '1'
	END AS GKFS
	, CASE
		WHEN (
			SELECT COUNT(1)
			FROM aea_hi_iteminst
			WHERE STAGEINST_ID = iteminst.STAGEINST_ID
		) > 1 THEN iteminst.STAGEINST_ID
		ELSE NULL
	END AS BLSPSLBM, asti.TIME_LIMIT AS SXBLSX, 1 AS SJYXBS
	, CASE
		WHEN iteminst.CREATE_TIME > asti.CREATE_TIME THEN iteminst.CREATE_TIME
		ELSE asti.CREATE_TIME
	END AS MODIFY_TIME
FROM AEA_HI_ITEMINST iteminst
	INNER JOIN ACT_STO_TIMERULE_INST asti
	ON asti.PROC_INST_ID = iteminst.PROCINST_ID
		AND asti.TIMERULE_INST_TYPE = '1'
	INNER JOIN AEA_HI_SERIESINST ahs ON ahs.SERIESINST_ID = iteminst.SERIESINST_ID
	INNER JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = ahs.APPLYINST_ID
	LEFT JOIN AEA_ITEM_VER aiv_123 ON aiv_123.ITEM_VER_ID = iteminst.ITEM_VER_ID
	LEFT JOIN AEA_ITEM_BASIC aib_123 ON aib_123.ITEM_VER_ID = iteminst.ITEM_VER_ID
	LEFT JOIN AEA_HI_APPLYINST aha_123 ON aha_123.APPLYINST_ID = ahs.APPLYINST_ID
	LEFT JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = aap.PROJ_INFO_ID
	LEFT JOIN AEA_PAR_THEME apt_123 ON apt_123.THEME_ID = proj.THEME_ID
	LEFT JOIN OPU_OM_ORG org ON org.ORG_ID = iteminst.APPROVE_ORG_ID
WHERE ahs.STAGE_ID IS NULL
	AND NOT EXISTS (
		SELECT 1
		FROM AEA_IM_PROJ_PURCHASE ipp
		WHERE ipp.APPLYINST_ID = ahs.APPLYINST_ID
	));

-- 3.5.2项目审批事项办理详细信息表
CREATE OR REPLACE VIEW SPGL_XMSPSXBLXXXXB_VIEW
AS
(SELECT '000000' AS XZQHDM, lish_123.STATE_HIST_ID AS DFSJZJ
	, replace(proj.GCBM, '#', '-') AS GCDM
	, lish_123.ITEMINST_ID AS SPSXSLBM, lish_123.OPS_USER_NAME AS BLR, ifnull((
		SELECT org.ORG_NAME
		FROM OPU_OM_USER_ORG ouo
			INNER JOIN OPU_OM_ORG org ON ouo.ORG_ID = org.ORG_ID
		WHERE USER_ID = lish_123.OPS_USER_ID
		LIMIT 1
	), lish_123.OPS_USER_NAME) AS BLCS
	, NEW_STATE AS BLZT
	, CASE
		WHEN IS_FLOW_TRIGGER = 1 THEN ifnull((
			SELECT ahc_123.MESSAGE_
			FROM ACT_HI_TASKINST aht_123
				LEFT JOIN ACT_HI_COMMENT ahc_123 ON ahc_123.TASK_ID_ = aht_123.ID_
			WHERE lish_123.TASKINST_ID = aht_123.ID_
		), '暂无意见')
		ELSE OPS_USER_OPINION
	END AS BLYJ, lish_123.TRIGGER_TIME AS BLSJ, 1 AS SJYXBS
	, CASE
		WHEN lish_123.TRIGGER_TIME > asti.CREATE_TIME THEN lish_123.TRIGGER_TIME
		ELSE asti.CREATE_TIME
	END AS MODIFY_TIME
FROM AEA_LOG_ITEM_STATE_HIST lish_123
	INNER JOIN AEA_HI_ITEMINST iteminst ON lish_123.ITEMINST_ID = iteminst.ITEMINST_ID
	INNER JOIN ACT_STO_TIMERULE_INST asti
	ON asti.PROC_INST_ID = iteminst.PROCINST_ID
		AND asti.TIMERULE_INST_TYPE = '1'
	INNER JOIN AEA_HI_PAR_STAGEINST hps ON hps.STAGEINST_ID = iteminst.STAGEINST_ID
	INNER JOIN AEA_PAR_STAGE stage
	ON stage.STAGE_ID = hps.STAGE_ID
		AND stage.IS_SHOW_ITEM != '0'
	INNER JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = hps.APPLYINST_ID
	LEFT JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = aap.PROJ_INFO_ID
WHERE lish_123.NEW_STATE <= 16)
UNION ALL
(SELECT '000000' AS XZQHDM, lish_123.STATE_HIST_ID AS DFSJZJ
	, replace(proj.GCBM, '#', '-') AS GCDM
	, lish_123.ITEMINST_ID AS SPSXSLBM, lish_123.OPS_USER_NAME AS BLR, ifnull((
		SELECT org.ORG_NAME
		FROM OPU_OM_USER_ORG ouo
			INNER JOIN OPU_OM_ORG org ON ouo.ORG_ID = org.ORG_ID
		WHERE USER_ID = lish_123.OPS_USER_ID
		LIMIT 1
	), lish_123.OPS_USER_NAME) AS BLCS
	, NEW_STATE AS BLZT
	, CASE
		WHEN IS_FLOW_TRIGGER = 1 THEN ifnull((
			SELECT ahc_123.MESSAGE_
			FROM ACT_HI_TASKINST aht_123
				LEFT JOIN ACT_HI_COMMENT ahc_123 ON ahc_123.TASK_ID_ = aht_123.ID_
			WHERE lish_123.TASKINST_ID = aht_123.ID_
		), '暂无意见')
		ELSE OPS_USER_OPINION
	END AS BLYJ, lish_123.TRIGGER_TIME AS BLSJ, 1 AS SJYXBS
	, CASE
		WHEN lish_123.TRIGGER_TIME > asti.CREATE_TIME THEN lish_123.TRIGGER_TIME
		ELSE asti.CREATE_TIME
	END AS MODIFY_TIME
FROM AEA_LOG_ITEM_STATE_HIST lish_123
	INNER JOIN AEA_HI_ITEMINST iteminst ON lish_123.ITEMINST_ID = iteminst.ITEMINST_ID
	INNER JOIN ACT_STO_TIMERULE_INST asti
	ON asti.PROC_INST_ID = iteminst.PROCINST_ID
		AND asti.TIMERULE_INST_TYPE = '1'
	INNER JOIN AEA_HI_SERIESINST ahs ON ahs.SERIESINST_ID = iteminst.SERIESINST_ID
	INNER JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = ahs.APPLYINST_ID
	LEFT JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = aap.PROJ_INFO_ID
WHERE lish_123.NEW_STATE <= 16
	AND NOT EXISTS (
		SELECT 1
		FROM AEA_IM_PROJ_PURCHASE ipp
		WHERE ipp.APPLYINST_ID = ahs.APPLYINST_ID
	));

-- 3.5.5项目审批事项批复文件信息表
CREATE OR REPLACE VIEW SPGL_XMSPSXPFWJXXB_VIEW
AS
(SELECT hii.INOUTINST_ID AS DFSJZJ, replace(proj.GCBM, '#', '-') AS GCDM
	, '000000' AS XZQHDM, hii.ITEMINST_ID AS SPSXSLBM, him.OFFICIAL_DOC_PUBLISH_DATE AS PFRQ, him.OFFICIAL_DOC_NO AS PFWH, him.OFFICIAL_DOC_TITLE AS PFWJBT
	, CASE
		WHEN length(trim(him.OFFICIAL_DOC_DUE_DATE)) > 0 THEN him.OFFICIAL_DOC_DUE_DATE
		ELSE str_to_date('9999-01-01', '%Y-%m-%d')
	END AS PFWJYXQX, detail.ATT_NAME AS FJMC, detail.DETAIL_ID AS FJID, detail.ATT_FORMAT AS FJLX, 1 AS SJYXBS
	, CASE
		WHEN him.MODIFY_TIME IS NULL
		OR him.MODIFY_TIME < hii.CREATE_TIME THEN hii.CREATE_TIME
		ELSE him.MODIFY_TIME
	END AS MODIFY_TIME
FROM AEA_HI_ITEM_INOUTINST hii
	INNER JOIN AEA_HI_ITEM_MATINST him ON him.MATINST_ID = hii.MATINST_ID
	INNER JOIN AEA_ITEM_MAT mat
	ON him.MAT_ID = mat.MAT_ID
		AND mat.IS_OFFICIAL_DOC = '1'
	INNER JOIN AEA_HI_ITEMINST iteminst ON iteminst.ITEMINST_ID = hii.ITEMINST_ID
	INNER JOIN AEA_HI_PAR_STAGEINST hps ON hps.STAGEINST_ID = iteminst.STAGEINST_ID
	INNER JOIN AEA_PAR_STAGE stage
	ON stage.STAGE_ID = hps.STAGE_ID
		AND stage.IS_SHOW_ITEM != '0'
	INNER JOIN BSC_ATT_LINK lk ON lk.RECORD_ID = hii.MATINST_ID
	INNER JOIN BSC_ATT_DETAIL detail ON lk.DETAIL_ID = detail.DETAIL_ID
	INNER JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = hps.APPLYINST_ID
	LEFT JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = aap.PROJ_INFO_ID)
UNION ALL
(SELECT hii.INOUTINST_ID AS DFSJZJ, replace(proj.GCBM, '#', '-') AS GCDM
	, '000000' AS XZQHDM, hii.ITEMINST_ID AS SPSXSLBM, him.OFFICIAL_DOC_PUBLISH_DATE AS PFRQ, him.OFFICIAL_DOC_NO AS PFWH, him.OFFICIAL_DOC_TITLE AS PFWJBT
	, CASE
		WHEN length(trim(him.OFFICIAL_DOC_DUE_DATE)) > 0 THEN him.OFFICIAL_DOC_DUE_DATE
		ELSE str_to_date('9999-01-01', '%Y-%m-%d')
	END AS PFWJYXQX, detail.ATT_NAME AS FJMC, detail.DETAIL_ID AS FJID, detail.ATT_FORMAT AS FJLX, 1 AS SJYXBS
	, CASE
		WHEN him.MODIFY_TIME IS NULL
		OR him.MODIFY_TIME < hii.CREATE_TIME THEN hii.CREATE_TIME
		ELSE him.MODIFY_TIME
	END AS MODIFY_TIME
FROM AEA_HI_ITEM_INOUTINST hii
	INNER JOIN AEA_HI_ITEM_MATINST him ON him.MATINST_ID = hii.MATINST_ID
	INNER JOIN AEA_ITEM_MAT mat
	ON him.MAT_ID = mat.MAT_ID
		AND mat.IS_OFFICIAL_DOC = '1'
	INNER JOIN AEA_HI_ITEMINST iteminst ON iteminst.ITEMINST_ID = hii.ITEMINST_ID
	INNER JOIN AEA_HI_SERIESINST ahs ON ahs.SERIESINST_ID = iteminst.SERIESINST_ID
	INNER JOIN BSC_ATT_LINK lk ON lk.RECORD_ID = hii.MATINST_ID
	INNER JOIN BSC_ATT_DETAIL detail ON lk.DETAIL_ID = detail.DETAIL_ID
	INNER JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = ahs.APPLYINST_ID
	LEFT JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = aap.PROJ_INFO_ID)
UNION ALL
(SELECT hii.INOUTINST_ID AS DFSJZJ, replace(proj.GCBM, '#', '-') AS GCDM
	, '000000' AS XZQHDM, hps.STAGEINST_ID AS SPSXSLBM, him.OFFICIAL_DOC_PUBLISH_DATE AS PFRQ, him.OFFICIAL_DOC_NO AS PFWH, him.OFFICIAL_DOC_TITLE AS PFWJBT
	, CASE
		WHEN length(trim(him.OFFICIAL_DOC_DUE_DATE)) > 0 THEN him.OFFICIAL_DOC_DUE_DATE
		ELSE str_to_date('9999-01-01', '%Y-%m-%d')
	END AS PFWJYXQX, detail.ATT_NAME AS FJMC, detail.DETAIL_ID AS FJID, detail.ATT_FORMAT AS FJLX, 1 AS SJYXBS
	, CASE
		WHEN him.MODIFY_TIME IS NULL
		OR him.MODIFY_TIME < hii.CREATE_TIME THEN hii.CREATE_TIME
		ELSE him.MODIFY_TIME
	END AS MODIFY_TIME
FROM AEA_HI_ITEM_INOUTINST hii
	INNER JOIN AEA_HI_ITEM_MATINST him ON him.MATINST_ID = hii.MATINST_ID
	INNER JOIN AEA_ITEM_MAT mat
	ON him.MAT_ID = mat.MAT_ID
		AND mat.IS_OFFICIAL_DOC = '1'
	INNER JOIN AEA_HI_ITEMINST iteminst ON iteminst.ITEMINST_ID = hii.ITEMINST_ID
	INNER JOIN AEA_HI_PAR_STAGEINST hps ON hps.STAGEINST_ID = iteminst.STAGEINST_ID
	INNER JOIN AEA_PAR_STAGE stage
	ON stage.STAGE_ID = hps.STAGE_ID
		AND stage.IS_SHOW_ITEM = '0'
	INNER JOIN BSC_ATT_LINK lk ON lk.RECORD_ID = hii.MATINST_ID
	INNER JOIN BSC_ATT_DETAIL detail ON lk.DETAIL_ID = detail.DETAIL_ID
	INNER JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = hps.APPLYINST_ID
	LEFT JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = aap.PROJ_INFO_ID);

-- 3.5.6项目其他附件信息表（包括申请材料，审批节点上传的附件）
CREATE OR REPLACE VIEW SPGL_XMQTFJXXB_VIEW
AS
SELECT XZQHDM, DFSJZJ
	, replace(proj.GCBM, '#', '-') AS GCDM
	, SPSXSLBM, BLSPSLBM, FJID, FJMC, FJFL
	, FJLX, SJYXBS, SPGL_XMQTFJXXB_TEMP.MODIFY_TIME
FROM (
	SELECT DISTINCT hii.INOUTINST_ID AS DFSJZJ, '000000' AS XZQHDM, hii.ITEMINST_ID AS SPSXSLBM
        , CASE
            WHEN (
                SELECT COUNT(1)
                FROM aea_hi_iteminst
                WHERE STAGEINST_ID = iteminst.STAGEINST_ID
            ) > 1 THEN iteminst.STAGEINST_ID
            ELSE NULL
        END AS BLSPSLBM, hps.APPLYINST_ID
		, detail.DETAIL_ID AS FJID, detail.ATT_NAME AS FJMC, 1 AS FJFL, detail.ATT_FORMAT AS FJLX, 1 AS SJYXBS
		, CASE
			WHEN hii.CREATE_TIME > asti.CREATE_TIME THEN hii.CREATE_TIME
			ELSE asti.CREATE_TIME
		END AS MODIFY_TIME
	FROM AEA_HI_ITEM_INOUTINST hii
		INNER JOIN AEA_HI_ITEMINST iteminst ON iteminst.ITEMINST_ID = hii.ITEMINST_ID
		INNER JOIN ACT_STO_TIMERULE_INST asti ON asti.PROC_INST_ID = iteminst.PROCINST_ID
		    AND asti.TIMERULE_INST_TYPE = '1'
		INNER JOIN AEA_HI_PAR_STAGEINST hps ON hps.STAGEINST_ID = iteminst.STAGEINST_ID
		INNER JOIN AEA_PAR_STAGE stage
		ON stage.STAGE_ID = hps.STAGE_ID
			AND stage.IS_SHOW_ITEM != '0'
		INNER JOIN BSC_ATT_LINK lk ON lk.RECORD_ID = hii.MATINST_ID
		INNER JOIN BSC_ATT_DETAIL detail ON lk.DETAIL_ID = detail.DETAIL_ID
		INNER JOIN AEA_HI_ITEM_MATINST him ON him.MATINST_ID = hii.MATINST_ID
		INNER JOIN AEA_ITEM_MAT mat
		ON him.MAT_ID = mat.MAT_ID
			AND mat.IS_OFFICIAL_DOC != '1'
	UNION ALL
	SELECT DISTINCT hii.INOUTINST_ID AS DFSJZJ, '000000' AS XZQHDM, hii.ITEMINST_ID AS SPSXSLBM, NULL AS BLSPSLBM, ahs.APPLYINST_ID
		, detail.DETAIL_ID AS FJID, detail.ATT_NAME AS FJMC, 1 AS FJFL, detail.ATT_FORMAT AS FJLX, 1 AS SJYXBS
		, CASE
			WHEN hii.CREATE_TIME > asti.CREATE_TIME THEN hii.CREATE_TIME
			ELSE asti.CREATE_TIME
		END AS MODIFY_TIME
	FROM AEA_HI_ITEM_INOUTINST hii
		INNER JOIN AEA_HI_ITEMINST iteminst ON iteminst.ITEMINST_ID = hii.ITEMINST_ID
		INNER JOIN ACT_STO_TIMERULE_INST asti ON asti.PROC_INST_ID = iteminst.PROCINST_ID
		    AND asti.TIMERULE_INST_TYPE = '1'
		INNER JOIN AEA_HI_SERIESINST ahs ON ahs.SERIESINST_ID = iteminst.SERIESINST_ID
		INNER JOIN BSC_ATT_LINK lk ON lk.RECORD_ID = hii.MATINST_ID
		INNER JOIN BSC_ATT_DETAIL detail ON lk.DETAIL_ID = detail.DETAIL_ID
		INNER JOIN AEA_HI_ITEM_MATINST him ON him.MATINST_ID = hii.MATINST_ID
		INNER JOIN AEA_ITEM_MAT mat
		ON him.MAT_ID = mat.MAT_ID
			AND mat.IS_OFFICIAL_DOC != '1'
	UNION ALL
	SELECT DISTINCT hii.INOUTINST_ID AS DFSJZJ, '000000' AS XZQHDM, hps.STAGEINST_ID AS SPSXSLBM, NULL AS BLSPSLBM, hps.APPLYINST_ID
		, detail.DETAIL_ID AS FJID, detail.ATT_NAME AS FJMC, 1 AS FJFL, detail.ATT_FORMAT AS FJLX, 1 AS SJYXBS
		, CASE
			WHEN hii.CREATE_TIME > asti.CREATE_TIME THEN hii.CREATE_TIME
			ELSE asti.CREATE_TIME
		END AS MODIFY_TIME
	FROM AEA_HI_ITEM_INOUTINST hii
		INNER JOIN AEA_HI_ITEMINST iteminst ON iteminst.ITEMINST_ID = hii.ITEMINST_ID
		INNER JOIN ACT_STO_TIMERULE_INST asti ON asti.PROC_INST_ID = iteminst.PROCINST_ID
		    AND asti.TIMERULE_INST_TYPE = '1'
		INNER JOIN AEA_HI_PAR_STAGEINST hps ON hps.STAGEINST_ID = iteminst.STAGEINST_ID
		INNER JOIN AEA_PAR_STAGE stage
		ON stage.STAGE_ID = hps.STAGE_ID
			AND stage.IS_SHOW_ITEM = '0'
		INNER JOIN BSC_ATT_LINK lk ON lk.RECORD_ID = hii.MATINST_ID
		INNER JOIN BSC_ATT_DETAIL detail ON lk.DETAIL_ID = detail.DETAIL_ID
		INNER JOIN AEA_HI_ITEM_MATINST him ON him.MATINST_ID = hii.MATINST_ID
		INNER JOIN AEA_ITEM_MAT mat
		ON him.MAT_ID = mat.MAT_ID
			AND mat.IS_OFFICIAL_DOC != '1'
) SPGL_XMQTFJXXB_TEMP
	INNER JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = SPGL_XMQTFJXXB_TEMP.APPLYINST_ID
	LEFT JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = aap.PROJ_INFO_ID;

-- 11.项目审批事项办理特别程序信息表
CREATE OR REPLACE VIEW SPGL_XMSPSXBLTBCXXXB_VIEW
AS
SELECT spec.SPECIAL_ID AS DFSJZJ, '000000' AS XZQHDM, proj.GCBM AS GCDM, spec.ITEMINST_ID AS SPSXSLBM
	, CASE spec.SPECIAL_TYPE
		WHEN '1' THEN '4'
		WHEN '2' THEN '1'
		WHEN '3' THEN '7'
		WHEN '4' THEN '2'
		WHEN '5' THEN '5'
	END AS TBCX
	, CASE spec.SPECIAL_TYPE
		WHEN '1' THEN '现场听证'
		WHEN '2' THEN '现场勘察'
		WHEN '3' THEN '招投标'
		WHEN '4' THEN '专家评审'
		WHEN '5' THEN '环评公示'
	END AS TBCXMC, lish.TRIGGER_TIME AS TBCXKSSJ, 1 AS TBCXSXLX, spec.SPECIAL_DUE_DAYS AS TBCXSX, 1 AS SJYXBS
	, ssh.CREATE_TIME AS MODIFY_TIME
FROM aea_hi_item_special spec
	INNER JOIN aea_hi_item_special_state_hist ssh ON ssh.SPECIAL_ID = spec.SPECIAL_ID
	INNER JOIN aea_log_item_state_hist lish
	ON lish.STATE_HIST_ID = ssh.STATE_HIST_ID
		AND lish.NEW_STATE = '9'
	LEFT JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = spec.PROJ_INFO_ID;

-- 15.中介服务事项办理信息表
CREATE OR REPLACE VIEW SPGL_ZJFWSXBLXXB_VIEW
AS
SELECT iteminst.ITEMINST_ID AS DFSJZJ, '000000' AS XZQHDM
	, replace(proj.LOCAL_CODE, '#', '-') AS XMDM
	, aib_123.ITEM_NAME AS ZJFWSXMC, aib_123.ITEM_CODE AS ZJFWSXBM, aib_123.STANDARD_ITEM_CODE AS DYBZZJFWSXBM, iteminst.ITEMINST_ID AS ZJFWSXSLBM, NULL AS SPSXSLBM
	, CASE asti.TIMERULE_UNIT
		WHEN asti.TIMERULE_UNIT IN ('WH', 'NH') THEN CEILING(asti.TIME_LIMIT / 24)
		ELSE asti.TIMERULE_UNIT
	END AS BLSX
	, CASE asti.TIMERULE_UNIT
		WHEN 'ND' THEN 2
		WHEN 'NH' THEN 2
		WHEN 'WD' THEN 1
		WHEN 'WH' THEN 1
	END AS SXLX, unit.UNIFIED_SOCIAL_CREDIT_CODE AS ZJJGDM, unit.APPLICANT AS ZJJGMC
	, CASE
		WHEN PUBLISH_UNIT_INFO_ID IS NULL THEN (
			SELECT LINKMAN_NAME
			FROM AEA_LINKMAN_INFO lxr
			WHERE lxr.LINKMAN_INFO_ID = ipp.PUBLISH_LINKMAN_INFO_ID
		)
		ELSE (
			SELECT APPLICANT
			FROM AEA_UNIT_INFO dw
			WHERE dw.UNIT_INFO_ID = ipp.PUBLISH_UNIT_INFO_ID
		)
	END AS WTR
	, CASE
		WHEN PUBLISH_UNIT_INFO_ID IS NULL THEN (
			SELECT LINKMAN_CERT_NO
			FROM AEA_LINKMAN_INFO lxr
			WHERE lxr.LINKMAN_INFO_ID = ipp.PUBLISH_LINKMAN_INFO_ID
		)
		ELSE (
			SELECT UNIFIED_SOCIAL_CREDIT_CODE
			FROM AEA_UNIT_INFO dw
			WHERE dw.UNIT_INFO_ID = ipp.PUBLISH_UNIT_INFO_ID
		)
	END AS WTRDM, 1 AS SJYXBS, asti.CREATE_TIME AS MODIFY_TIME
FROM AEA_HI_ITEMINST iteminst
	INNER JOIN ACT_STO_TIMERULE_INST asti ON asti.PROC_INST_ID = iteminst.PROCINST_ID
	INNER JOIN AEA_HI_SERIESINST ahs ON ahs.SERIESINST_ID = iteminst.SERIESINST_ID
	INNER JOIN AEA_IM_PROJ_PURCHASE ipp ON ipp.APPLYINST_ID = ahs.APPLYINST_ID
	INNER JOIN AEA_IM_UNIT_BIDDING bid
	ON bid.PROJ_PURCHASE_ID = ipp.PROJ_PURCHASE_ID
		AND IS_WON_BID = '1'
	INNER JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = ahs.APPLYINST_ID
	LEFT JOIN AEA_UNIT_INFO unit ON unit.UNIT_INFO_ID = bid.UNIT_INFO_ID
	LEFT JOIN AEA_ITEM_BASIC aib_123 ON aib_123.ITEM_VER_ID = iteminst.ITEM_VER_ID
	LEFT JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = aap.PROJ_INFO_ID;

-- 16.中介服务事项办理过程信息表
CREATE OR REPLACE VIEW SPGL_ZJFWSXBLGCXXB_VIEW
AS
SELECT '000000' AS XZQHDM, lish_123.STATE_HIST_ID AS DFSJZJ
	, replace(proj.LOCAL_CODE, '#', '-') AS XMDM
	, lish_123.ITEMINST_ID AS ZJFWSXSLBM, 1 AS BLZT, lish_123.OPS_USER_NAME AS BLR
	, CASE
		WHEN IS_FLOW_TRIGGER = 1 THEN ifnull((
			SELECT ahc_123.MESSAGE_
			FROM ACT_HI_TASKINST aht_123
				LEFT JOIN ACT_HI_COMMENT ahc_123 ON ahc_123.TASK_ID_ = aht_123.ID_
			WHERE lish_123.TASKINST_ID = aht_123.ID_
		), '暂无意见')
		ELSE OPS_USER_OPINION
	END AS BLYJ, lish_123.TRIGGER_TIME AS BLSJ,NULL AS FJMC ,NULL AS FJID, 1 AS SJYXBS
	, CASE
		WHEN lish_123.TRIGGER_TIME > asti.CREATE_TIME THEN lish_123.TRIGGER_TIME
		ELSE asti.CREATE_TIME
	END AS MODIFY_TIME
FROM AEA_LOG_ITEM_STATE_HIST lish_123
	INNER JOIN AEA_HI_ITEMINST iteminst ON lish_123.ITEMINST_ID = iteminst.ITEMINST_ID
	INNER JOIN ACT_STO_TIMERULE_INST asti ON asti.PROC_INST_ID = iteminst.PROCINST_ID
	    AND asti.TIMERULE_INST_TYPE = '1'
	INNER JOIN AEA_HI_SERIESINST ahs ON ahs.SERIESINST_ID = iteminst.SERIESINST_ID
	INNER JOIN AEA_IM_PROJ_PURCHASE ipp ON ipp.APPLYINST_ID = ahs.APPLYINST_ID
	INNER JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = ahs.APPLYINST_ID
	LEFT JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = aap.PROJ_INFO_ID
WHERE lish_123.NEW_STATE = '8'
UNION ALL
SELECT '000000' AS XZQHDM, lish_123.STATE_HIST_ID AS DFSJZJ
	, replace(proj.LOCAL_CODE, '#', '-') AS XMDM
	, lish_123.ITEMINST_ID AS ZJFWSXSLBM, 2 AS BLZT, lish_123.OPS_USER_NAME AS BLR
	, CASE
		WHEN IS_FLOW_TRIGGER = 1 THEN ifnull((
			SELECT ahc_123.MESSAGE_
			FROM ACT_HI_TASKINST aht_123
				LEFT JOIN ACT_HI_COMMENT ahc_123 ON ahc_123.TASK_ID_ = aht_123.ID_
			WHERE lish_123.TASKINST_ID = aht_123.ID_
		), '暂无意见')
		ELSE OPS_USER_OPINION
	END AS BLYJ, lish_123.TRIGGER_TIME AS BLSJ,NULL AS FJMC ,NULL AS FJID, 1 AS SJYXBS
	, CASE
		WHEN lish_123.TRIGGER_TIME > asti.CREATE_TIME THEN lish_123.TRIGGER_TIME
		ELSE asti.CREATE_TIME
	END AS MODIFY_TIME
FROM AEA_LOG_ITEM_STATE_HIST lish_123
	INNER JOIN AEA_HI_ITEMINST iteminst ON lish_123.ITEMINST_ID = iteminst.ITEMINST_ID
	INNER JOIN ACT_STO_TIMERULE_INST asti ON asti.PROC_INST_ID = iteminst.PROCINST_ID
	    AND asti.TIMERULE_INST_TYPE = '1'
	INNER JOIN AEA_HI_SERIESINST ahs ON ahs.SERIESINST_ID = iteminst.SERIESINST_ID
	INNER JOIN AEA_IM_PROJ_PURCHASE ipp ON ipp.APPLYINST_ID = ahs.APPLYINST_ID
	INNER JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = ahs.APPLYINST_ID
	LEFT JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = aap.PROJ_INFO_ID
WHERE lish_123.NEW_STATE IN ('4','5','11','12','13','14','15');

-- --------------------------------------------------------------------------BEGIN
-- 辅线事项 -- --------------------------------------------------------------------------

CREATE OR REPLACE VIEW spgl_dfxmsplcjdfxsxxxb_view
AS
SELECT stage.STAGE_ID AS DFSJZJ, '000000' AS XZQHDM, theme.THEME_CODE AS SPLCBM, theme.VER_NUM AS SPLCBBH, 5 AS SPJDXH
	, stage.STAGE_CODE AS SPSXBM, themever.VER_NUM AS SPSXBBH, stage.STAGE_NAME AS SPSXMC, '9990' AS DYBZSPSXBM, '0' AS SFSXGZCNZ
	, '3' AS BJLX, '6' AS SQDX, '2,3' AS BLJGSDFS, stage.DUE_NUM AS SPSXBLSX
	, (
		SELECT opu_om_org.ORG_CODE
		FROM opu_om_org
		WHERE stage.ROOT_ORG_ID = opu_om_org.ORG_ID
	) AS SPBMBM
	, (
		SELECT opu_om_org.ORG_NAME
		FROM opu_om_org
		WHERE stage.ROOT_ORG_ID = opu_om_org.ORG_ID
	) AS SPBMMC, 0 AS SFLCBSX, 1 AS SJYXBS
	, CASE
		WHEN stage.MODIFY_TIME IS NOT NULL THEN stage.MODIFY_TIME
		ELSE stage.CREATE_TIME
	END AS MODIFY_TIME
FROM AEA_HI_PAR_STAGEINST hps
	INNER JOIN AEA_PAR_STAGE stage ON stage.STAGE_ID = hps.STAGE_ID
	INNER JOIN aea_par_theme_ver themever ON themever.THEME_VER_ID = stage.THEME_VER_ID
	INNER JOIN AEA_APPLYINST_PROJ ahai123 ON ahai123.APPLYINST_ID = hps.APPLYINST_ID
	LEFT JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = ahai123.PROJ_INFO_ID
	LEFT JOIN THEME_MAX_VER theme ON theme.THEME_ID = proj.THEME_ID
WHERE stage.IS_SHOW_ITEM = '0'
	AND stage.IS_NODE = '2';

-- 辅线事项办理信息
CREATE OR REPLACE VIEW SPGL_XMSPFXSXBLXXB_VIEW
AS
SELECT stageinst.stageinst_id AS DFSJZJ, '000000' AS XZQHDM
	, replace(proj.GCBM, '#', '-') AS GCDM
	, stage.STAGE_CODE AS SPSXBM, themever.VER_NUM AS SPSXBBH, theme.THEME_CODE AS SPLCBM, theme.VER_NUM AS SPLCBBH, stageinst.stageinst_id AS SPSXSLBM
	, org.ORG_CODE AS SPBMBM, org.ORG_NAME AS SPBMMC
	, CASE applyinst.APPLYINST_SOURCE
		WHEN 'net' THEN 4
		WHEN 'win' THEN 1
	END AS SLFS, 1 AS GKFS, NULL AS BLSPSLBM
	, (
		SELECT flowdef.TIME_LIMIT
		FROM act_tpl_app_flowdef flowdef
		WHERE flowdef.APP_ID = stage.APP_ID
			AND flowdef.IS_MASTER = '1'
	) AS SXBLSX, 1 AS SJYXBS
	, CASE
		WHEN stageinst.MODIFY_TIME IS NOT NULL THEN stageinst.MODIFY_TIME
		ELSE stageinst.CREATE_TIME
	END AS MODIFY_TIME
FROM aea_hi_par_stageinst stageinst
	JOIN AEA_HI_APPLYINST applyinst ON applyinst.APPLYINST_ID = stageinst.APPLYINST_ID
	JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = applyinst.APPLYINST_ID
	JOIN aea_proj_info proj ON proj.proj_info_id = aap.proj_info_id
	JOIN aea_par_stage stage ON stage.STAGE_ID = stageinst.STAGE_ID
	JOIN aea_par_theme_ver themever ON themever.THEME_VER_ID = stage.THEME_VER_ID
	LEFT JOIN THEME_MAX_VER theme ON theme.THEME_ID = proj.THEME_ID
	LEFT JOIN opu_om_org org ON org.org_id = stageinst.ROOT_ORG_ID
WHERE stage.IS_SHOW_ITEM = '0'
	AND stage.IS_NODE = '2';

-- 辅线事项办理详细信息
CREATE OR REPLACE VIEW SPGL_XMSPFXSXBLXXXXB_VIEW
AS
SELECT *
FROM (
	SELECT *
	FROM (
		SELECT lish_123.STATE_HIST_ID AS DFSJZJ, '000000' AS XZQHDM
			, replace(proj.GCBM, '#', '-') AS GCDM
			, stageinst.stageinst_id AS SPSXSLBM, ifnull((
				SELECT org.ORG_NAME
				FROM OPU_OM_USER_ORG ouo
					INNER JOIN OPU_OM_ORG org ON ouo.ORG_ID = org.ORG_ID
				WHERE USER_ID = lish_123.OPS_USER_ID
				LIMIT 1
			), lish_123.OPS_USER_NAME) AS BLCS, lish_123.OPS_USER_NAME AS BLR
			, NEW_STATE AS BLZT
			, CASE
				WHEN IS_FLOW_TRIGGER = 1 THEN ifnull((
					SELECT ahc_123.MESSAGE_
					FROM ACT_HI_TASKINST aht_123
						LEFT JOIN ACT_HI_COMMENT ahc_123 ON ahc_123.TASK_ID_ = aht_123.ID_
					WHERE lish_123.TASKINST_ID = aht_123.ID_
					LIMIT 1
				), '暂无意见')
				ELSE OPS_USER_OPINION
			END AS BLYJ, lish_123.TRIGGER_TIME AS BLSJ, 1 AS SJYXBS
			, CASE
				WHEN lish_123.TRIGGER_TIME > asti.CREATE_TIME THEN lish_123.TRIGGER_TIME
				ELSE asti.CREATE_TIME
			END AS MODIFY_TIME
		FROM AEA_LOG_ITEM_STATE_HIST lish_123
			INNER JOIN AEA_HI_ITEMINST iteminst ON lish_123.ITEMINST_ID = iteminst.ITEMINST_ID
			INNER JOIN ACT_STO_TIMERULE_INST asti ON asti.PROC_INST_ID = iteminst.PROCINST_ID
			    AND asti.TIMERULE_INST_TYPE = '1'
			INNER JOIN AEA_HI_PAR_STAGEINST stageinst ON stageinst.STAGEINST_ID = iteminst.STAGEINST_ID
			INNER JOIN AEA_PAR_STAGE stage
			ON stage.STAGE_ID = stageinst.STAGE_ID
				AND stage.IS_SHOW_ITEM = '0'
				AND stage.IS_NODE = '2'
			INNER JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = stageinst.APPLYINST_ID
			INNER JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = aap.PROJ_INFO_ID
		WHERE lish_123.NEW_STATE IN ('1', '2', '3', '4', '5', '8')
		ORDER BY lish_123.TRIGGER_TIME ASC
	) a
	UNION ALL
	SELECT *
	FROM (
		SELECT lish_123.STATE_HIST_ID AS DFSJZJ, '000000' AS XZQHDM
			, replace(proj.GCBM, '#', '-') AS GCDM
			, stageinst.stageinst_id AS SPSXSLBM, ifnull((
				SELECT org.ORG_NAME
				FROM OPU_OM_USER_ORG ouo
					INNER JOIN OPU_OM_ORG org ON ouo.ORG_ID = org.ORG_ID
				WHERE USER_ID = lish_123.OPS_USER_ID
				LIMIT 1
			), lish_123.OPS_USER_NAME) AS BLCS, lish_123.OPS_USER_NAME AS BLR
			, NEW_STATE AS BLZT
			, CASE
				WHEN IS_FLOW_TRIGGER = 1 THEN ifnull((
					SELECT ahc_123.MESSAGE_
					FROM ACT_HI_TASKINST aht_123
						LEFT JOIN ACT_HI_COMMENT ahc_123 ON ahc_123.TASK_ID_ = aht_123.ID_
					WHERE lish_123.TASKINST_ID = aht_123.ID_
					LIMIT 1
				), '暂无意见')
				ELSE OPS_USER_OPINION
			END AS BLYJ, lish_123.TRIGGER_TIME AS BLSJ, 1 AS SJYXBS
			, CASE
				WHEN lish_123.TRIGGER_TIME > asti.CREATE_TIME THEN lish_123.TRIGGER_TIME
				ELSE asti.CREATE_TIME
			END AS MODIFY_TIME
		FROM AEA_LOG_ITEM_STATE_HIST lish_123
			INNER JOIN AEA_HI_ITEMINST iteminst ON lish_123.ITEMINST_ID = iteminst.ITEMINST_ID
			INNER JOIN ACT_STO_TIMERULE_INST asti ON asti.PROC_INST_ID = iteminst.PROCINST_ID
			    AND asti.TIMERULE_INST_TYPE = '1'
			INNER JOIN AEA_HI_PAR_STAGEINST stageinst ON stageinst.STAGEINST_ID = iteminst.STAGEINST_ID
			INNER JOIN AEA_PAR_STAGE stage
			ON stage.STAGE_ID = stageinst.STAGE_ID
				AND stage.IS_SHOW_ITEM = '0'
				AND stage.IS_NODE = '2'
			INNER JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = stageinst.APPLYINST_ID
			INNER JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = aap.PROJ_INFO_ID
		WHERE lish_123.NEW_STATE IN ('11', '12', '13', '14', '15')
		ORDER BY lish_123.TRIGGER_TIME DESC
	) b
) TEMP
GROUP BY GCDM, SPSXSLBM, BLZT
UNION ALL
SELECT lish_123.STATE_HIST_ID AS DFSJZJ, '000000' AS XZQHDM
	, replace(proj.GCBM, '#', '-') AS GCDM
	, stageinst.stageinst_id AS SPSXSLBM, ifnull((
		SELECT org.ORG_NAME
		FROM OPU_OM_USER_ORG ouo
			INNER JOIN OPU_OM_ORG org ON ouo.ORG_ID = org.ORG_ID
		WHERE USER_ID = lish_123.OPS_USER_ID
		LIMIT 1
	), lish_123.OPS_USER_NAME) AS BLCS, lish_123.OPS_USER_NAME AS BLR
	, NEW_STATE AS BLZT
	, CASE
		WHEN IS_FLOW_TRIGGER = 1 THEN ifnull((
			SELECT ahc_123.MESSAGE_
			FROM ACT_HI_TASKINST aht_123
				LEFT JOIN ACT_HI_COMMENT ahc_123 ON ahc_123.TASK_ID_ = aht_123.ID_
			WHERE lish_123.TASKINST_ID = aht_123.ID_
			LIMIT 1
		), '暂无意见')
		ELSE OPS_USER_OPINION
	END AS BLYJ, lish_123.TRIGGER_TIME AS BLSJ, 1 AS SJYXBS
	, CASE
		WHEN lish_123.TRIGGER_TIME > asti.CREATE_TIME THEN lish_123.TRIGGER_TIME
		ELSE asti.CREATE_TIME
	END AS MODIFY_TIME
FROM AEA_LOG_ITEM_STATE_HIST lish_123
	INNER JOIN AEA_HI_ITEMINST iteminst ON lish_123.ITEMINST_ID = iteminst.ITEMINST_ID
	INNER JOIN ACT_STO_TIMERULE_INST asti ON asti.PROC_INST_ID = iteminst.PROCINST_ID
	    AND asti.TIMERULE_INST_TYPE = '1'
	INNER JOIN AEA_HI_PAR_STAGEINST stageinst ON stageinst.STAGEINST_ID = iteminst.STAGEINST_ID
	INNER JOIN AEA_PAR_STAGE stage
	ON stage.STAGE_ID = stageinst.STAGE_ID
		AND stage.IS_SHOW_ITEM = '0'
		AND stage.IS_NODE = '2'
	INNER JOIN AEA_APPLYINST_PROJ aap ON aap.APPLYINST_ID = stageinst.APPLYINST_ID
	INNER JOIN AEA_PROJ_INFO proj ON proj.PROJ_INFO_ID = aap.PROJ_INFO_ID
WHERE lish_123.NEW_STATE IN ('6', '7');
-- --------------------------------------------------------------------------辅线事项 END
-- --------------------------------------------------------------------------